-- MySQL Script generated by MySQL Workbench
-- Sat Jun 17 14:44:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projeto_academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto_academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto_academia` DEFAULT CHARACTER SET utf8 ;
USE `projeto_academia` ;

-- -----------------------------------------------------
-- Table `projeto_academia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto_academia`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `loginUser` VARCHAR(10) NOT NULL,
  `passUser` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
